language: ruby
bundler_args: --without development
script: 'rake appraisal test'
services:
  - mongodb
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
- ruby-head
env:
- DB=mongodb
- DB=redis
- DB=mysql
#- DB=postgres
before_script:
- "mysql -e 'create database vanity_test;' >/dev/null"
- "rake appraisal:install"
#- "psql -c 'create database vanity_test;' -U postgres >/dev/null"
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: ruby-head
